### ISSUE TITLE
How do you install this plugin using composer? (Craft 3)

### ISSUE THREAD

**Issue by RosanaRufer** [clubstudioltd/craft-asset-rev#17]
Sorry for opening an issue for this but I just don't find how to install it. When I run `composer require clubstudioltd/craft-asset-rev` the same command but using the composer.json handle or name it says:

![image](https://user-images.githubusercontent.com/4906291/32115216-df5dc9c6-bb3d-11e7-9a7b-620897f54bea.png)

**Comment by scottwakefield** [comment]
Hi @Totemika,

Thanks for opening this issue. I'm in the middle of migrating the Craft 3 code from the other repo into this repo, in order to follow the same conventions that Pixel & Tonic are using for their first-party plugins.

I'll be adding the relevant `composer.json` file to the `v6` branch and setting that branch as the default in the near future. 

I'll also be deprecating the other Craft 3 repo at the same time.

Sorry if this was confusing in the meantime. I'll leave this issue open until I've made the necessary updates.

👍

**Comment by RosanaRufer** [comment]
Oh, I see. I thought it was the other way around (from this branch to a new repo). Thanks.

**Comment by scottwakefield** [comment]
Hey @Totemika,

You should be good to go now: https://packagist.org/packages/clubstudioltd/craft-asset-rev 👍 

Let me know if that's all ok now.
