### ISSUE TITLE
Do the files need to exist?

### ISSUE THREAD

**Issue by lxcodes** [clubstudioltd/craft-asset-rev#8]
Currently hitting an issue where we have javascripts that are hot-reloaded and not an actual file served from the file system but generated and inserted by a node server.  Would it be possible, either by configuration variable or something else, to just ignore that a file may not exist and still output a query string of random to just cache bust?

**Comment by scottwakefield** [comment]
Hi @al3x-edge,

Sure, I can look at adding a configuration option that when true will allow the plugin to fallback to using a random query string. Initial intentions were to always throw an error when the plugin couldn't do what it needed to, so that people didn't miss assets not loading etc. With that in mind, I think a configuration is the way to go.

Leave it with me, or feel free to open a pull request 👍

**Comment by lxcodes** [comment]
@scottwakefield I'll try for a PR in a bit / today.  I have a partial implementation but will need to add in configuration stuff.
